### ISSUE TITLE
about the 5G and UWB frequency.

### ISSUE THREAD

**Issue by AICrazy** [Decawave/uwb-core#11]
Hello, I am the developer of DW1000. I checked the information and found that the 5G frequency band and many channel frequency bands of DW1000 overlap. I want to ask you something: Will the upcoming 5G affect UWB ultra-wideband communication?

thank u :)

**Comment by ncasaril** [comment]
Hi AlCrazy, 

Yes it will. Especially when the uwb transceiver is in close proximity to a 5G transmitter. This is why uwb channel 9 (~8GHz) may be a better choice in the future as well as rf filtering. 

Cheers,
Niklas
