### ISSUE TITLE
Multiple Rules for Single Object File Prevents Parallel Compilation

### ISSUE THREAD

**Issue by eliptus-google** [Decawave/uwb-core#14]
Multiple modules attempt to build streamer.o with different paths but the same canonical path, causing race conditions in parallelized build:
https://github.com/Decawave/uwb-core/blob/8ffba63755a932a89d841872ce5bdf35b9c78777/Kbuild#L55
https://github.com/Decawave/uwb-core/blob/8ffba63755a932a89d841872ce5bdf35b9c78777/apps/uwb_desense/Kbuild#L23

**Comment by ncasaril** [comment]
Thanks Eli, 
I will push a fix when public-repo freeze is removed.

**Comment by Guilhem23** [comment]
@ncasaril should be fixed now as desense apps has been removed ?
